### ISSUE TITLE
Error in onReady: Error: Not connect to jablonet.net

### ISSUE THREAD

**Issue by valbuz** [DEV2DEV-DE/ioBroker.jablotron#11]
**Describe the bug**  
Error in onReady: Error: Not connect to jablonet.net

**To Reproduce**  
Nach jedem Start der Instanz

**Versions:**  
 - Adapter version: 0.1.0
 - JS-Controller version: 5.0.16
 - Node version: 18.19.0
 - Operating system: debian

**Comment by DEV2DEV-DE** [comment]
Sind im Benutzernamen/Kennwort Sonderzeichen enthalten?
Vielleicht mal einen weiteren Account zum Testen anlegen, der ohne Sonderzeichen auskommt.
Wenn das dann funktioniert, kann ich mir Gedanken machen wie das zu umgehen wäre.

**Comment by valbuz** [comment]
Ja ich habe natürlich Sonderzeichen.
Habe nun einen Account ohne Sonderzeichen erstellt. Mit diesem kann ich mich auch online auf myjablotron einloggen.
Die Instanz hat immer noch denselben Fehler....

**Comment by DEV2DEV-DE** [comment]
Gerade mit der neuesten Version von GitHub getestet:
![image](https://github.com/DEV2DEV-DE/ioBroker.jablotron/assets/95883579/1d30d118-88d0-48c3-8b21-34d8107765d8)
Kommt da irgend eine Art von Fehlermeldung? Also ein HTTP-403 oder etwas in der Art?

**Comment by DEV2DEV-DE** [comment]
OK, der Adapter schafft es also nicht, in 4 Sekunden eine Antwort von Jablotron zu erhalten.
Scheint mir prinzipiell kein Problem des Adapters, sondern der vorhandenen Infrastruktur.

Darf der ioBroker da überhaupt hin? Hindert ihn möglicherweise eine Firewall?
Wie ist das Ganze installiert? Auf 'nem Pi, Docker-Container, Proxmox?

Ein einfacher Request per Blockly mit dem URL https://api.jablonet.net/api/2.2
sollte etwas in der Art liefern:
![image](https://github.com/DEV2DEV-DE/ioBroker.jablotron/assets/95883579/c8afe96a-27d1-4273-82a9-91ab74de9f55)

**Comment by DEV2DEV-DE** [comment]
Die Instanz am besten auf Logstufe "debug" stellen. Dann sieht man mehr!

**Comment by valbuz** [comment]
Hier das Log:

`15.12.2023, 12:36:44.264	[info ]: javascript.0 (86438) Stop script script.js.common.Jablotron
15.12.2023, 12:36:49.973	[info ]: javascript.0 (86438) Start javascript script.js.common.Jablotron
15.12.2023, 12:36:49.988	[info ]: javascript.0 (86438) script.js.common.Jablotron: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
15.12.2023, 12:36:57.276	[info ]: javascript.0 (86438) script.js.common.Jablotron: <?xml version="1.0" encoding="utf-8"?>
<xml><http-code>400</http-code><errors><error><code>APPLICATION.NO-PERMISSION</code><message>This application is no longer supported, please download newer version.</message><debug>APP tries to use unknown API version 2.2</debug></error></errors><meta><display-type>TOAST</display-type></meta></xml>

15.12.2023, 12:36:57.276	[info ]: javascript.0 (86438) script.js.common.Jablotron: null`

**Comment by DEV2DEV-DE** [comment]
Das heißt, es dauert bei Dir **über 7 Sekunden !!!** bis Du eine Antwort vom Server erhältst :-(

![grafik](https://github.com/DEV2DEV-DE/ioBroker.jablotron/assets/95883579/9cfbe686-f3e7-45eb-8ede-a5c81fb0dbea)
Mit solchen Antwortzeiten ist das Ganze nicht wirklich sinnvoll einsetzbar.

Hier zum Vergleich mal mein Log:
```
10:33:57.970 | info | javascript.0 (5036) Start javascript script.js.common.Test-Blockly
10:33:58.108 | info | javascript.0  (5036) script.js.common.Test-Blockly: registered 0 subscriptions, 0  schedules, 0 messages, 0 logs and 0 file subscriptions
10:33:58.379 | info | javascript.0  (5036) script.js.common.Test-Blockly: <?xml version="1.0"  encoding="utf-8"?>...</xml>
```
Es dauert nur ca. 0,5 Sekunden bis die Antwort kommt.

Wie bist Du denn da internetmäßig angebunden?
Das sieht mir extrem langsam aus.

**Comment by valbuz** [comment]
Habe es nun auf einem anderen System probiert.
Hier läuft alles wie es soll!

Danke!
