### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.1.1

### ISSUE THREAD

**Issue by GermanBluefox** [DEV2DEV-DE/ioBroker.jablotron#16]
# Think about adding version 0.1.1 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.1.1** (30 days old)
**Installs**: stable=**0** (0%), latest=**18** (90%), total=**20**

Click to use [developer portal](https://www.iobroker.dev/adapter/jablotron/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by DEV2DEV-DE** [comment]
Version 0.1.3 is now going to stable repo.
