### ISSUE TITLE
Wunsch-Erweiterung  / Klartext Anzeige

### ISSUE THREAD

**Issue by tokenobi** [DEV2DEV-DE/ioBroker.jablotron#9]
Über OpenHab hatte ich schon einmal Jablotron am laufen bekommen. Was ich dann im Anschluss auch über den ioBroker OpenHab Adapter in ioB intrigieren konnte. Als eines von vielen Objekten wurde mir ein String Wert angezeigt, in dem jede Aktion angezeigt wurde. Z.B. : "Schlafzimmer auf" ....... Einbruchmeldeanlage an ...... (Genauen Wortlaut kann ich leider nicht mehr wiedergeben.

Ist das vielleicht auch möglich ?

**Comment by DEV2DEV-DE** [comment]
@tokenobi 
Hast Du den Adapter mal getestet und Dir die angelegten Datenpunkte angeschaut?

![grafik](https://github.com/DEV2DEV-DE/ioBroker.jablotron/assets/95883579/e83a8c48-8e0b-4655-9b67-8a6023158ff6)

**Comment by tokenobi** [comment]
Ja, doch das funktioniert auch alles super. Ist auch nicht so wichtig. Ich kann mich daran erinnern das auch die Scharfschaltverzögerung usw. angezeigt wurde.

**Comment by DEV2DEV-DE** [comment]
Man kann natürlich Änderungen an ausgewählten DP jederzeit auch selbst überwachen und den Klartext in einen eigenen DP schreiben ;-)

![image](https://github.com/DEV2DEV-DE/ioBroker.jablotron/assets/95883579/91e28855-48d2-4e98-ae7f-166887d37790)

**Comment by DEV2DEV-DE** [comment]
Ich mache hier mal zu.
Da der Adapter nur die "programmable gates" ohne einen Kontext kennt, macht es mehr Sinn das per Script selbst zusammenzubauen.
